name: m_watchlist
description: Flutter App
version: 1.0.0
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  m_core:
    path: ../m_core
  dartz: ^0.10.0
  flutter:
    sdk: flutter

dev_dependencies:
  bloc_test: ^9.0.0-dev.3
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter: null
